### ISSUE TITLE
KeyError: 'true_false'

### ISSUE THREAD

**Issue by zcy1234321** [amazon-science/mm-cot#36]
** CUDA_VISIBLE_DEVICES=0,1 python main.py \
    --model allenai/unifiedqa-t5-base \
    --user_msg rationale --img_type detr \
    --bs 4 --eval_bs 2 --eval_acc 10 --output_len 512 \
    --final_eval --prompt_format QCM-LE

**When running the above code, an error is reported, please ask which part of the data true_false in****

_Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'true_false'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 381, in <module>
    args = args
  File "main.py", line 312, in T5Trainer
    scores = get_scores(results_ans, results_rationale, results_reference, os.path.join(args.data_root, "scienceqa/problems.json"))
  File "/home/featurize/work/mm-cot/mm-cot-main/utils_evaluate.py", line 54, in get_scores
    print(res_pd['true_false'])
  File "/environment/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/environment/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'true_false'_

**Comment by zcy1234321** [comment]
![image](https://user-images.githubusercontent.com/53549311/223141260-5dff2427-16e1-47a8-9a5e-c9730be83264.png)

**Comment by cashmere0** [comment]
same problem with u. may I ask do u solve it now？thank u！
